<?php
// Access constants
define('OAUTH_ACCESS_TOKEN', 'YOUR_OAUTH_ACCESS_TOKEN');
define('OAUTH_ACCESS_TOKEN_SECRET', 'YOUR_OAUTH_ACCESS_TOKEN_SECRET');
define('CONSUMER_KEY', 'YOUR_CONSUMER_KEY');
define('CONSUMER_SECRET', 'YOUR_CONSUMER_SECRET');